version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=/api
    networks:
      - tournament-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
    volumes:
      - tournament-data:/app/data
    networks:
      - tournament-network
    restart: unless-stopped

networks:
  tournament-network:
    driver: bridge

volumes:
  tournament-data:
    driver: local